CREATE TABLE `USER` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE METRICS (
    id INT,
    WPM FLOAT NOT NULL,
    CPE FLOAT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES `USER`(id) ON DELETE CASCADE
);

CREATE TABLE PAIRS (
    id INT,
    pair CHAR(2) NOT NULL,
    `interval` FLOAT NOT NULL,
    PRIMARY KEY (id, pair),
    FOREIGN KEY (id) REFERENCES `USER`(id) ON DELETE CASCADE
);